#!/usr/bin/env python3
"""Generate or verify the CPython 3.12 test locks without rewriting authority."""

from __future__ import annotations

import argparse
import hashlib
import platform
import subprocess
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "requirements-test-py312.in"
LOCKS = {
    "windows": ROOT / "requirements-test-py312-windows-lock.txt",
    "linux": ROOT / "requirements-test-py312-linux-lock.txt",
}
UV_VERSION = "0.11.16"
PYTHON_VERSION = (3, 12, 10)


def _input_sha256() -> str:
    return hashlib.sha256(INPUT.read_bytes()).hexdigest().upper()


def verify_runtime_dependency_input(
    input_path: Path = INPUT,
    pyproject_path: Path = ROOT / "pyproject.toml",
) -> None:
    """Require the current test input to repeat runtime dependencies verbatim."""
    try:
        project = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
        expected = project["project"]["dependencies"]
    except (OSError, KeyError, TypeError, tomllib.TOMLDecodeError) as exc:
        raise SystemExit(f"cannot read runtime dependency authority: {exc}") from exc
    if not isinstance(expected, list) or not all(isinstance(value, str) for value in expected):
        raise SystemExit("pyproject runtime dependencies are invalid")
    try:
        actual = [
            line.strip()
            for line in input_path.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]
    except OSError as exc:
        raise SystemExit(f"cannot read test dependency input: {exc}") from exc
    runtime = actual[: len(expected)]
    if runtime != expected:
        raise SystemExit(
            "requirements-test-py312.in runtime dependencies drift from pyproject.toml"
        )


def _require_generator_runtime() -> None:
    if sys.version_info[:3] != PYTHON_VERSION:
        raise SystemExit(
            "refusing to generate test locks: requires CPython 3.12.10, got "
            f"{platform.python_implementation()} {platform.python_version()}"
        )
    result = subprocess.run(["uv", "--version"], text=True, capture_output=True, check=False)
    if result.returncode != 0 or not result.stdout.startswith(f"uv {UV_VERSION} "):
        raise SystemExit(
            f"refusing to generate test locks: requires uv {UV_VERSION}; "
            f"got {result.stdout.strip() or result.stderr.strip() or 'unavailable'}"
        )


def _compile(platform_name: str, destination: Path) -> None:
    command = [
        "uv", "pip", "compile", str(INPUT), "--python-version", "3.12",
        "--python-platform", platform_name, "--generate-hashes", "--no-header",
        "--output-file", str(destination),
    ]
    result = subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False)
    if result.returncode:
        raise SystemExit(result.stderr or result.stdout)
    body = destination.read_text(encoding="utf-8")
    if "--hash=sha256:" not in body:
        raise SystemExit(f"refusing unhashed {platform_name} lock")
    header = (
        f"# Generated by tools/generate_test_locks.py with CPython 3.12.10 and uv {UV_VERSION}.\n"
        f"# Command: uv pip compile requirements-test-py312.in --python-version 3.12 --python-platform {platform_name} --generate-hashes.\n"
        f"# Input: requirements-test-py312.in sha256={_input_sha256()}\n"
        f"# Target: {platform_name}; regenerate only with this command and review the diff.\n"
    )
    destination.write_text(header + body, encoding="utf-8", newline="\n")


def _verify_lock(platform_name: str, lock: Path) -> None:
    if not lock.is_file():
        raise SystemExit(f"missing {lock.name}; run tools/generate_test_locks.py")
    required = (
        f"CPython 3.12.10 and uv {UV_VERSION}",
        f"sha256={_input_sha256()}",
        f"Target: {platform_name}",
        "--hash=sha256:",
    )
    body = lock.read_text(encoding="utf-8")
    missing = [value for value in required if value not in body]
    if missing:
        raise SystemExit(f"invalid {lock.name}: missing {', '.join(missing)}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true")
    arguments = parser.parse_args()
    verify_runtime_dependency_input()
    if arguments.verify:
        for platform_name, lock in LOCKS.items():
            _verify_lock(platform_name, lock)
        return
    _require_generator_runtime()
    for platform_name, lock in LOCKS.items():
        _compile(platform_name, lock)
    for platform_name, lock in LOCKS.items():
        _verify_lock(platform_name, lock)


if __name__ == "__main__":
    main()
