"""Stable, fail-closed errors for the Stage 7 QCIS compiler."""

from __future__ import annotations

from enum import StrEnum


class QCISReasonCode(StrEnum):
    NONCANONICAL_SOURCE = "QCIS_NONCANONICAL_SOURCE"
    NONCANONICAL_NUMBER = "QCIS_NONCANONICAL_NUMBER"
    UNKNOWN_OPERATION = "QCIS_UNKNOWN_OPERATION"
    UNKNOWN_QAGENT = "QCIS_UNKNOWN_QAGENT"
    ARITY_MISMATCH = "QCIS_ARITY_MISMATCH"
    TEMPLATE_ID_MISMATCH = "QCIS_TEMPLATE_ID_MISMATCH"
    TEMPLATE_SHA_MISMATCH = "QCIS_TEMPLATE_SHA_MISMATCH"
    BINDING_SET_MISMATCH = "QCIS_BINDING_SET_MISMATCH"
    BINDING_POSITION_FORBIDDEN = "QCIS_BINDING_POSITION_FORBIDDEN"
    BINDING_UNIT_MISMATCH = "QCIS_BINDING_UNIT_MISMATCH"
    TIMING_OVERLAP = "QCIS_TIMING_OVERLAP"
    TIMING_OUT_OF_BUDGET = "QCIS_TIMING_OUT_OF_BUDGET"
    CARRIER_CHANGE_UNSUPPORTED = "QCIS_CARRIER_CHANGE_UNSUPPORTED"
    MACRO_CALIBRATION_INCOMPLETE = "QCIS_MACRO_CALIBRATION_INCOMPLETE"
    CALIBRATION_AUTHORITY_HASH_MISMATCH = "QCIS_CALIBRATION_AUTHORITY_HASH_MISMATCH"
    PROFILE_AUTHORITY_HASH_MISMATCH = "QCIS_PROFILE_AUTHORITY_HASH_MISMATCH"
    QAGENT_AUTHORITY_HASH_MISMATCH = "QCIS_QAGENT_AUTHORITY_HASH_MISMATCH"
    GATE_CONFIG_AUTHORITY_HASH_MISMATCH = "QCIS_GATE_CONFIG_AUTHORITY_HASH_MISMATCH"
    WAVEFORM_REGISTRY_AUTHORITY_HASH_MISMATCH = "QCIS_WAVEFORM_REGISTRY_AUTHORITY_HASH_MISMATCH"
    CLOCK_AUTHORITY_HASH_MISMATCH = "QCIS_CLOCK_AUTHORITY_HASH_MISMATCH"
    COMPILER_AUTHORITY_HASH_MISMATCH = "QCIS_COMPILER_AUTHORITY_HASH_MISMATCH"
    MEASUREMENT_STAGE8_REQUIRED = "QCIS_MEASUREMENT_STAGE8_REQUIRED"
    LOGICAL_WAVEFORM_HASH_MISMATCH = "QCIS_LOGICAL_WAVEFORM_HASH_MISMATCH"
    EFFECTIVE_CONTROL_HASH_MISMATCH = "STAGE4_1_EFFECTIVE_CONTROL_HASH_MISMATCH"
    COEFFICIENT_INVENTORY_MISMATCH = "STAGE5_1_COEFFICIENT_INVENTORY_MISMATCH"
    UNSUPPORTED_NUMERIC_WAVEFORM = "QCIS_UNSUPPORTED_NUMERIC_WAVEFORM"
    UNSUPPORTED_WAVE_INDEX = "QCIS_UNSUPPORTED_WAVE_INDEX"


class QCISCompilationError(ValueError):
    """An admitted QCIS operation failed a stable, externally visible contract."""

    def __init__(self, code: QCISReasonCode, detail: str = "") -> None:
        self.code = code
        self.detail = detail
        super().__init__(f"{code}: {detail}" if detail else str(code))

